name: Scheduled benchmarking, reporting and publishing
on:
  schedule:
          # Run twice daily at 5:05 am and 8:05 pm
    - cron: '05 5,20 * * *'

jobs:
  benchmarks_x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: SSH to CI instance to run benchmarks
        run: |
          set -e
          set -x
          export AWS_INSTANCE=${{ secrets.CI_AWS_INSTANCE }}
          cat << EOF > ./id_benchmark_ci_rsa
          ${{ secrets.AWS_INSTANCE_PRIVATE_KEY }}
          EOF
          chmod go-rwx ./id_benchmark_ci_rsa
          export SSH_ARGS="-o StrictHostKeyChecking=no -i ./id_benchmark_ci_rsa -o TCPKeepAlive=yes -o ServerAliveCountMax=20 -o ServerAliveInterval=15"
          ssh $SSH_ARGS ubuntu@$AWS_INSTANCE "cd ym/yjit-metrics && git pull"
          ssh $SSH_ARGS ubuntu@$AWS_INSTANCE "bash -l -c './ym/yjit-metrics/continuous_reporting/benchmark_prep_task.sh'"
          ssh $SSH_ARGS ubuntu@$AWS_INSTANCE "bash -l -c './ym/yjit-metrics/continuous_reporting/benchmark_only_cron_task.sh'"
  reporting_and_upload:
    runs-on: ubuntu-latest
    needs: [benchmarks_x86]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: SSH to CI instance to run reports and upload results
        env:
          BENCHMARK_CI_GITHUB_TOKEN: ${{ secrets.BENCHMARK_CI_GITHUB_TOKEN }}
        run: |
          set -e
          set -x
          export AWS_INSTANCE=${{ secrets.CI_AWS_INSTANCE }}
          cat << EOF > ./id_benchmark_ci_rsa
          ${{ secrets.AWS_INSTANCE_PRIVATE_KEY }}
          EOF
          chmod go-rwx ./id_benchmark_ci_rsa
          export SSH_ARGS="-o StrictHostKeyChecking=no -i ./id_benchmark_ci_rsa -o TCPKeepAlive=yes -o ServerAliveCountMax=20 -o ServerAliveInterval=15"
          ssh $SSH_ARGS ubuntu@$AWS_INSTANCE "cd ym/yjit-metrics && git pull"
          ssh $SSH_ARGS ubuntu@$AWS_INSTANCE "bash -l -c 'BENCHMARK_CI_GITHUB_TOKEN=$BENCHMARK_CI_GITHUB_TOKEN ./ym/yjit-metrics/continuous_reporting/benchmark_upload_cron_task.sh'"
