name: Scheduled benchmarking, reporting and publishing
on:
  schedule:
    # Run twice daily at 7:05 am/pm
    - cron: '05 7,19 * * *'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: SSH to CI instance to start benchmarking and publication
        run: |
          set -e
          set -x
          git pull
          export BENCHMARK_CI_GITHUB_TOKEN=${{ secrets.BENCHMARK_CI_GITHUB_TOKEN }}
          export BENCHMARK_CI_GITHUB_USER=${{ secrets.BENCHMARK_CI_GITHUB_USER }}
          export AWS_INSTANCE=${{ secrets.CI_AWS_INSTANCE }}
          cat << EOF > ./id_benchmark_ci_rsa
          ${{ secrets.AWS_INSTANCE_PRIVATE_KEY }}
          EOF
          chmod go-rwx ./id_benchmark_ci_rsa
          ssh -o StrictHostKeyChecking=no -i ./id_benchmark_ci_rsa ubuntu@$AWS_INSTANCE "ls"
          ssh -o StrictHostKeyChecking=no -i ./id_benchmark_ci_rsa ubuntu@$AWS_INSTANCE "BENCHMARK_CI_GITHUB_TOKEN=$BENCHMARK_CI_GITHUB_TOKEN BENCHMARK_CI_GITHUB_USER=$BENCHMARK_CI_GITHUB_USER ./ym/yjit-metrics/continuous_reporting/benchmark_cron_task.sh"

